# Generated by Django 5.2.5 on 2025-09-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
